homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 26
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York

  customize:
    sensor.yr_symbol:
      alias: weather
    light.t1:
      assumed_state: false
      icon: mdi:lightbulb
    light.t2:
      assumed_state: false
      icon: mdi:lightbulb
    light.t3:
      assumed_state: false
      icon: mdi:lightbulb
    light.d1:
      assumed_state: false
      icon: mdi:lightbulb
    light.d2:
      assumed_state: false
      icon: mdi:lightbulb
    light.d3:
      assumed_state: false
      icon: mdi:lightbulb
    light.mood:
      assumed_state: false
      icon: mdi:lightbulb
    light.b1:
      assumed_state: false
      icon: mdi:lightbulb
    light.b2:
      assumed_state: false
      icon: mdi:lightbulb
    light.k1:
      assumed_state: false
      icon: mdi:lightbulb
    light.k2:
      assumed_state: false
      icon: mdi:lightbulb
    switch.playstation:
      entity_picture: /local/playstation.png
    switch.home_mode:
      entity_picture: /local/lightsOn.png
    switch.SleepMode:
      entity_picture: /local/goodnight.png
    switch.TV:
      entity_picture: /local/tv.png
    switch.DinnerMode:
      entity_picture: /local/dinner.png
    switch.GameMode:
      entity_picture: /local/520571-dice-512.png
    switch.speakers:
      entity_picture: /local/speakers.png
    switch.away:
      entity_picture: /local/away.png
    scene.AllOn:
      entity_picture: /local/lightsOn.png
    scene.AllOff:
      entity_picture: /local/away.png
    scene.dimmedLights:
      entity_picture: /local/lightsOff.png
# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_password
  server_port: 8123
  # Uncomment this if you are using SSL or running in Docker etc
  #base_url: michaelcomputer.duckdns.org:8124
  #ssl_certificate: '/etc/letsencrypt/live/michaelcomputer.duckdns.org/fullchain.pem'
  #ssl_key: '/etc/letsencrypt/live/michaelcomputer.duckdns.org/privkey.pem'

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor: !include sensors.yaml

# Text to speech
tts:
  platform: google

# mqtt
mqtt:
  broker: localhost
  port: 1883
  #client_id: HA
  #username: !secret mosquitto_username
  #password: !secret mosquitto_pw

input_select:
  home_mode:
    name: Home Mode
    options:
      - "Home"
      - "Away"
      - "Playstation"
      - "TV"
      - "Boardgame"
      - "Dinner"
      - "Evening"
      - "Goodnight"
    icon: mdi:target

# smartthings MQTT devices
switch: !include switches.yaml

light: !include lights.yaml

group: !include groups.yaml

scene: !include scenes.yaml


# scripts to delay speakers turning on/off
script: !include scripts.yaml


automation: !include automations.yaml
